server:
  port: 80


#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    #mysql5.x的没有cj
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #记得先创建数据库
#    url: jdbc:mysql://localhost:3306/db2022?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #表示是否将自己注册进EurekaServer  默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true.单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka  #集群版


